### PR TITLE
Add support for muting on start

### PR DESCRIPTION
**Pull request by somini**
With the -M option, you can start the program already muted, and unmute
it as usual.

This is mainly so that I can autostart this and unmute it when I want to
show off.

### CODE REVIEW

**Comment by Natureshadow** [comment]
Indentation seems to be broken, looking at it on GitHub.

**Comment by somini** [comment]
Thanks for the heads up, I force pushed the fix.

**Comment by somini** [comment]
Friendly ping

**Comment by zevv** [comment]
Sorry for the delay, I seemed to have missed the original request.

**Pull request merged**
