### PR TITLE
Ogg Vorbis support via libvorbisfile

### PR DESCRIPTION
**Pull request by Member1221**
Still needs some work, but this loads the ogg files dynamically, adjusting for bitrate and channel count.

### CODE REVIEW

**Comment by Member1221** [comment]
@zevv Could you review my changes?

**Comment by zevv** [comment]
Sorry for the delay, I'll look into it!

**Comment by zevv** [comment]
Well, works for me and the code looks ok. Can you explain your rationale for this patch?

Advantages:
- Smaller database size
- any more?

Disadvantages:
- More dependencies
- any more?

Is reducing 6 mb to 1.7 mb of data size a problem worth solving with the added compexity and dependencies?

**Comment by Member1221** [comment]
Advantage is also that the format is more known-good and is more flexible (runtime detection of bitrate, etc.)

Haven't gotten responses from people in terms of if it fixed their issues with high CPU usage, but i expect it would be solved (audio files are 4.11 khz, so less resampling required.)

**Comment by zevv** [comment]
Quoting Clipsey (2019-02-11 11:15:20)

> Advantage is also that the format is more known-good and is more
> flexible (runtime detection of bitrate, etc.)

Ah, so you resample to the OpenAL samplerate and format at load time,
that should help.

You're confident enough to have this merged to master, or shall I merge
to a branch first so we can let others do some testing first?
 
--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by Member1221** [comment]
I think we should merge to a branch first and make a note in README.md that it could use some testing.

**Comment by Member1221** [comment]
Also no, but the OpenAL bitrate is set to the bitrate of the ogg stream, meaning OpenAL does the resampling instead of the driver.

**Comment by zevv** [comment]
Agree, that sounds like the way to go: create a branch and add some notes so people can test this.
If you could rebase your branch to master I can do a clean merge and we're good to go.

**Comment by Member1221** [comment]
Uhh i merged my changes so there's no more conflicts, is this ok. I'm not *too* experienced with git.

**Comment by Member1221** [comment]
By the way, it's already on a branch called ogg

**Comment by zevv** [comment]
Merged to `ogg` branch. Thanks!

**Comment by Member1221** [comment]
oh oops, i added something to the readme on the ogg branch, can you pull those changes? (just small ogg section)

**Comment by Member1221** [comment]
Wait you have, nevermind. xD

**Pull request closed without merging**
