### PR TITLE
Various fixes for Win32/MinGW

### PR DESCRIPTION
**Pull request by DankRank**
It works properly now

### CODE REVIEW

**Comment by zevv** [comment]
Sweet, thanks for looking into that.

What was the actual cause of the crash, I assume this was solved by dynamic linking Alure?

**Comment by DankRank** [comment]
That's correct, linking alure dynamically fixed the crash.

**Comment by zevv** [comment]
Quoting Egor (2017-06-23 19:12:30)

> That's correct, linking alure dynamically fixed the crash.

Ok, thanks. Any idea why this happens? Is static linking on win32
fundamentally different from Linux?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by DankRank** [comment]
I believe it's binary incompatibility between stdlibc++ and official alure binaries. I tried to compile alure from source, but that didn't work either - it compiled but all of the codecs (including codec_wav) were missing for some reason.

Either way, using dynamic library sidesteps all of those issues, as it already includes it's own compatible copy of stdlibc++.

**Comment by zevv** [comment]
Quoting Egor (2017-06-23 20:12:33)
> I believe it's binary incompatibility between stdlibc++ and official
> alure binaries. I tried to compile alure from source, but that didn't
> work either - it compiled but all of the codecs (including codec_wav)
> were missing for some reason.
> 
> Either way, using dynamic library sidesteps all of those issues, as it
> already includes it's own compatible copy of stdlibc++.

Ok, that makes sense.

I guess I'll have to build and distribute the binary in releases, since
most of the windows folks are probably not really accustomed to building
stuff from source.

Thanks for figuring this out!

--
:wq
^X^Cy^K^X^C^C^C^C

**Pull request merged**
