### PR TITLE
add mute_scroll, clean whitespace

### PR DESCRIPTION
**Pull request by dmitrii-galantsev**
Scrolling sound is pretty annoying on laptops. Added a flag to disable it.
Also cleaned up stray whitespaces.

### CODE REVIEW

**Comment by zevv** [comment]
I must admit I never really liked it as well. Could you update the PR to make the flag *enable* the scroll sound and disable it by default?

**Comment by zevv** [comment]
Oh and please take out the whitespace updates. The style used in this codebase simply has no space after `if`s and `for`s, and these kind of commits only add to the noise in the history.

Thanks!

**Comment by dmitrii-galantsev** [comment]
Great, I'll do that! Trying to figure out how to do edit the pull request.

**Comment by dmitrii-galantsev** [comment]
ok I think this will do it!
it also disables mouse clicks as a side effect, but I'm not sure how to differentiate between clicks and scrolling.

**Comment by zevv** [comment]
Hi Dmitrii,

Thanks for your update - but I'm afraid I solved it differently: the scroll sounds were an unintended side effect of a poorly implemented and tested feature: since scrolls generate mouse click events on 'virtual' buttons scrolling simply generated a whole bunch of click sounds - simply wrong.

I added a check for the mouse button pressed and now only play for left and right.

Thanks!

**Pull request closed without merging**
