### PR TITLE
Keypad samples

### PR DESCRIPTION
**Pull request by vain**
I recorded the sound of the keypad keys on my Model M:

https://gist.github.com/vain/7218352b9cb8d4d76b3141f27ce6f1ad

I'm not 100% sure if I edited `keyloc` correctly. Note that my keyboard has a german layout. You might want to re-check that. :-)

CC #16

### CODE REVIEW

**Comment by zevv** [comment]
Hi,

* On 2016-10-31 10:38:41 +0100, vain wrote:
 
> I recorded the sound of the keypad keys on my Model M:
> 
> https://gist.github.com/vain/7218352b9cb8d4d76b3141f27ce6f1ad

Thanks for that! Initially I was afraid that it would be necessary to
record all samples new instead of adding a few because of different mic
characteristics and room ambience, but your samples do pretty much fit
in the original set. 

The only problem is that my original samples were not normalized to 0 dB
like yours, so there's a difference in volume.  The best solution is
probably to normalize mine as well so that all keys play nicely at the
same level.

> I'm not 100% sure if I edited `keyloc` correctly. Note that my
> keyboard has a german layout. You might want to re-check that. :-)

I believe that doesn't make a different for the numpad area. The whole
keyboard layout thing is something that is absolutely not handled
properly, I just did the minimal to support my own computer, and I
wonder why so few people have complained about layout mismatches yet :)
 

-- 
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
Hmm pretty tricky to do this right, it seems. If I normalize my own samples the background noise level of each key gets a noticeable difference, which is kind of annoying. I guess I'll just have to reduce the gain of your new keys slightly so they fit in with the current set...

**Comment by zevv** [comment]
Merged!

**Comment by vain** [comment]
Yes, background noise is kind of an issue. Best way to solve this is to use an additional tool that plays some kind of data center noise or something like that ... ;-)

Glad I could help.

**Comment by Natureshadow** [comment]
> Yes, background noise is kind of an issue. Best way to solve this is to use an additional tool that plays some kind of data center noise or something like that ... ;-)

:D

**Pull request merged**
